name:                pushbullet-automation-haskell
version:             0.1.0.0
github:              "timTam97/pushbullet-automation-haskell"
license:             BSD3
author:              "Timothy Samraj"
copyright:           "2020 Timothy Samraj"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/timTam97/pushbullet-automation-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- websockets
- network
- mtl
- text
- Win32
- wuss
- aeson
- monad-loops
- bytestring
- req
- utf8-string
- time
- ormolu
- http-client
- process
- time

library:
  source-dirs: src

executables:
  pushbullet-automation-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -optl-mwindows
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - pushbullet-automation-haskell

tests:
  pushbullet-automation-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pushbullet-automation-haskell
